version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${postgres}
      POSTGRES_PASSWORD: ${1234}
      POSTGRES_DB: ${linkedin_insights}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
